const ingredients = [
  {
    id: 1,
    name: "Chicken Breast",
    icon: "🍗",
    category: "Protein",
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    servingSize: "100g",
    storage: "Refrigerated",
    inStock: true,
  },
  {
    id: 2,
    name: "Brown Rice",
    icon: "🍚",
    category: "Grains",
    calories: 112,
    protein: 2.6,
    carbs: 24,
    fat: 0.9,
    servingSize: "100g",
    storage: "Pantry",
    inStock: true,
  },
  {
    id: 3,
    name: "Broccoli",
    icon: "🥦",
    category: "Vegetables",
    calories: 34,
    protein: 2.8,
    carbs: 7,
    fat: 0.4,
    servingSize: "100g",
    storage: "Refrigerated",
    inStock: true,
  },
  {
    id: 4,
    name: "Salmon",
    icon: "🐟",
    category: "Protein",
    calories: 208,
    protein: 20,
    carbs: 0,
    fat: 13,
    servingSize: "100g",
    storage: "Refrigerated",
    inStock: false,
  },
  {
    id: 5,
    name: "Sweet Potato",
    icon: "🍠",
    category: "Vegetables",
    calories: 86,
    protein: 1.6,
    carbs: 20,
    fat: 0.1,
    servingSize: "100g",
    storage: "Pantry",
    inStock: true,
  },
  {
    id: 6,
    name: "Greek Yogurt",
    icon: "🥛",
    category: "Dairy",
    calories: 59,
    protein: 10,
    carbs: 3.6,
    fat: 0.4,
    servingSize: "100g",
    storage: "Refrigerated",
    inStock: true,
  },
  {
    id: 7,
    name: "Avocado",
    icon: "🥑",
    category: "Fruits",
    calories: 160,
    protein: 2,
    carbs: 9,
    fat: 15,
    servingSize: "100g",
    storage: "Room Temp",
    inStock: true,
  },
  {
    id: 8,
    name: "Almonds",
    icon: "🥜",
    category: "Nuts",
    calories: 579,
    protein: 21,
    carbs: 22,
    fat: 49,
    servingSize: "100g",
    storage: "Pantry",
    inStock: false,
  },
  {
    id: 9,
    name: "Spinach",
    icon: "🥬",
    category: "Vegetables",
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    servingSize: "100g",
    storage: "Refrigerated",
    inStock: true,
  },
  {
    id: 10,
    name: "Eggs",
    icon: "🥚",
    category: "Protein",
    calories: 155,
    protein: 13,
    carbs: 1.1,
    fat: 11,
    servingSize: "100g",
    storage: "Refrigerated",
    inStock: true,
  },
  {
    id: 11,
    name: "Quinoa",
    icon: "🌾",
    category: "Grains",
    calories: 120,
    protein: 4.4,
    carbs: 21,
    fat: 1.9,
    servingSize: "100g",
    storage: "Pantry",
    inStock: true,
  },
  {
    id: 12,
    name: "Blueberries",
    icon: "🫐",
    category: "Fruits",
    calories: 57,
    protein: 0.7,
    carbs: 14,
    fat: 0.3,
    servingSize: "100g",
    storage: "Refrigerated",
    inStock: false,
  },
];

export const defaultState = {
  apiEndpoint: "https://api.dietplanner.com/v1",
  syncInterval: 300,
  maxRecipesPerPage: 20,
  enableAnalytics: true,
  theme: {
    primaryColor: "#0284c7",
    accentColor: "#f97316",
  },
  ingredients: ingredients,
  recipes: [
    {
      id: 1,
      name: "Oatmeal Breakfast Bowl",
      description:
        "A wholesome and nutritious breakfast bowl packed with fiber, protein, and natural sweetness. Perfect for starting your day with sustained energy.",
      calories: 320,
      protein: 12,
      carbs: 55,
      fat: 8,
      time: 10,
      icon: "🥣",
      ingredients: [
        "1 cup rolled oats",
        "2 cups almond milk",
        "1 banana, sliced",
        "1/2 cup mixed berries",
        "2 tbsp honey",
        "1 tbsp chia seeds",
        "1/4 cup chopped walnuts",
        "Pinch of cinnamon",
      ],
      instructions: [
        "In a medium saucepan, bring the almond milk to a gentle simmer over medium heat.",
        "Add the rolled oats and reduce heat to low. Stir occasionally for 5-7 minutes until the oats are soft and creamy.",
        "Remove from heat and stir in the chia seeds and cinnamon.",
        "Transfer the oatmeal to a serving bowl.",
        "Top with sliced banana, mixed berries, chopped walnuts, and drizzle with honey.",
        "Serve warm and enjoy your nutritious breakfast bowl!",
      ],
      tags: ["Breakfast", "Vegetarian", "High Fiber", "Quick"],
    },
    {
      id: 2,
      name: "Greek Salad",
      description:
        "A refreshing Mediterranean classic featuring crisp vegetables, tangy feta cheese, and briny olives dressed in olive oil and herbs.",
      calories: 280,
      protein: 15,
      carbs: 18,
      fat: 18,
      time: 15,
      icon: "🥗",
      ingredients: [
        "2 large tomatoes, diced",
        "1 cucumber, diced",
        "1 red onion, thinly sliced",
        "1 green bell pepper, diced",
        "1 cup Kalamata olives",
        "200g feta cheese, cubed",
        "3 tbsp extra virgin olive oil",
        "1 tbsp red wine vinegar",
        "1 tsp dried oregano",
        "Salt and pepper to taste",
      ],
      instructions: [
        "Wash and prepare all the vegetables. Dice the tomatoes, cucumber, and bell pepper into bite-sized pieces.",
        "Thinly slice the red onion and rinse under cold water to reduce sharpness.",
        "In a large salad bowl, combine the tomatoes, cucumber, bell pepper, red onion, and Kalamata olives.",
        "Add the cubed feta cheese on top of the vegetables.",
        "In a small bowl, whisk together the olive oil, red wine vinegar, oregano, salt, and pepper.",
        "Drizzle the dressing over the salad and gently toss to combine. Serve immediately.",
      ],
      tags: ["Lunch", "Vegetarian", "Mediterranean", "No Cook"],
    },
    {
      id: 3,
      name: "Grilled Chicken Breast",
      description:
        "Perfectly seasoned and grilled chicken breast with aromatic herbs. A lean protein powerhouse that is versatile and delicious.",
      calories: 380,
      protein: 45,
      carbs: 5,
      fat: 18,
      time: 25,
      icon: "🍗",
      ingredients: [
        "2 chicken breasts (about 200g each)",
        "2 tbsp olive oil",
        "2 cloves garlic, minced",
        "1 tsp dried thyme",
        "1 tsp dried rosemary",
        "1 tsp paprika",
        "1/2 tsp black pepper",
        "1 tsp salt",
        "Juice of 1 lemon",
      ],
      instructions: [
        "Pat the chicken breasts dry with paper towels. If they are thick, butterfly them to ensure even cooking.",
        "In a bowl, mix together the olive oil, minced garlic, thyme, rosemary, paprika, pepper, salt, and lemon juice.",
        "Rub the marinade all over the chicken breasts and let them sit for at least 15 minutes at room temperature.",
        "Preheat your grill or grill pan to medium-high heat.",
        "Place the chicken breasts on the grill and cook for 6-7 minutes on each side, or until the internal temperature reaches 165°F (74°C).",
        "Remove from the grill and let the chicken rest for 5 minutes before slicing. Serve with your favorite vegetables or salad.",
      ],
      tags: ["Dinner", "High Protein", "Gluten Free", "Low Carb"],
    },
  ],
  features: {
    advancedFiltering: true,
    socialSharing: false,
    mealPlanExport: true,
  },
};
